# source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# user specific environment
if ! [[ "${PATH}" =~ "${HOME}/.local/bin:${HOME}/bin:" ]]
then
	PATH="${HOME}/.local/bin:${HOME}/bin:${PATH}"
fi
export PATH

# user specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "${rc}" ]; then
			. "${rc}"
		fi
	done
fi

unset rc

# set default terminal text editor
export VISUAL=micro
export EDITOR="${VISUAL}"

# don't search for commands on failure
unset command_not_found_handle