# connection
client_id = "65b708073fc0480ea92a077233ca87bd"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"

# playback string
playback_format = "{status} {track} · {artists}\n{album}\n{metadata}"

# limits
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20

# icons
play_icon = ""
pause_icon = ""
liked_icon = "󰋑"

# ui
theme = "clitify"
border_type = "Rounded"
progress_bar_type = "Rectangle"

# audio backend
enable_streaming = "Always"
default_device = "spotify-player"

seek_duration_secs = 5

[layout]
# playback window
playback_window_position = "Top"
playback_window_height = 5

# library columns ratio
library = { playlist_percent = 50, album_percent = 25 }

[device]
name = "spotify-player"
device_type = "speaker"

volume = 100
bitrate = 320

audio_cache = false
normalization = false
autoplay = true
